spring:
  application:
    name: gateway
  
  cloud:
    gateway:
      routes:
        - id: all-recipes
          uri: http://recetas:8083
          predicates:
            - Path=/recipes
        - id: recipes
          uri: http://recetas:8083
          predicates:
            - Path=/recipes/{id}
          filters:
            - SetPath=/recipes/{id}
